### ISSUE TITLE
Bug: Shulker Boxes inside Dispensers don't get placed

### ISSUE THREAD

**Issue by CommanderLP9809** [Bumer-32/Redstone-Helper#85]
**Describe the bug**
If you put a shulker box inside a dispenser and then power the dispenser, the shulker box doesn't get placed how it should be. Instead, the dispenser just spits out the particles and the shulker box remains inside the dispenser. Also if you put normal items inside the dispenser alsongside the shulker box, all items get dispensed and in the end the shulker remains in the dispenser and doesn't get placed or dropped.

**To Reproduce**
1. Put a shulker box in a dispenser
2. Power the dispenser
3. The Shulker box remains in the dispenser but particles come out of the dispenser

**Expected behavior**
The shulker box should get placed in front of the dispenser.

**Screenshots**
https://medal.tv/de/games/minecraft/clips/iP5xuBSXwIPcRTir1?invite=cr-MSxETlEsMjE3MTAyMzk2LA

**Some client**
Minecraft version: 1.21
Mod version: 0.2.5.2
Fabric version: 0.16.3
Dependencies versions Fabric Language Kotlin: 1.12.2+kotlin.2.0.20 ; owolib 0.12.14 ; Fabric API 102.0
Other installed mods: None, (tested with other mods and with only redstone helper)
It was tested in Singleplayer.

**Additional context**
LOG: 
[11:01:47] [Server thread/ERROR]: Error trying to place shulker box at class_2338{x=-38, y=56, z=222}
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at net.minecraft.class_1747.handler$bab000$redstone-helper$place(class_1747.java:520) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7708(class_1747.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:76) ~[client-intermediary.jar:?]
	at net.minecraft.class_2970.method_10135(class_2970.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_2347.dispense(class_2347.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_2315.method_10012(class_2315.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_2315.method_9588(class_2315.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1149) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_14189(class_3218.java:759) ~[client-intermediary.jar:?]
	at net.minecraft.class_6757.method_39390(class_6757.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_6757.method_39377(class_6757.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Bumer-32** [comment]
Thanks for the report! This should be fixed in version 0.2.5.3. Please update Redstone-Helper.

Resolution: Redstone-Helper is "searching" for the player for every block placement, including dispensers, but a dispenser ≠ player.

**Comment by CommanderLP9809** [comment]
Thank you so much for the quick response, fix and explanation. 
And thanks for the mod it is really helpful to me!
